apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: mypipline
build:
  local:
    push: true
  artifacts:
  - image: danielsavage1/backend
    context: backend
    docker:
      dockerfile: Dockerfile
  - image: danielsavage1/frontend
    context: ui/very_basic_ui
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/api-cluster-ip-service.yaml
    - k8s/api-deployment.yaml
    - k8s/client-cluster-ip-deployment.yaml
    - k8s/client-deployment.yaml
    - k8s/ingress-service.yaml
# deploy:
#   kustomize:
#     paths:
#       - ./deploy/dev

# profiles:
#   - name: production
#     deploy:
#       kustomize:
#         paths:
#           - ./deploy/prod

#   - name: staging
#     deploy:
#       kustomize:
#         paths:
#           - ./deploy/stg